### ISSUE TITLE
✖ Error: Command failed: /bin/sh -c autoreconf -ivf

### ISSUE THREAD

**Issue by RebornQ** [yrpang/github-actions-hexo#4]
这是日志：

```bash
/usr/local/bin/hexo -> /usr/local/lib/node_modules/hexo-cli/bin/hexo
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules/hexo-cli/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ hexo-cli@4.2.0
added 61 packages from 315 contributors in 3.041s

> core-js@2.6.11 postinstall /github/workspace/node_modules/babel-polyfill/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"


> core-js@2.6.11 postinstall /github/workspace/node_modules/babel-runtime/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"


> ejs@2.7.4 postinstall /github/workspace/node_modules/ejs
> node ./postinstall.js


> gifsicle@4.0.1 postinstall /github/workspace/node_modules/gifsicle
> node lib/install.js


  ⚠ spawn /github/workspace/node_modules/gifsicle/vendor/gifsicle ENOENT
  ⚠ gifsicle pre-build test failed
  ℹ compiling from source
  ✖ Error: Command failed: /bin/sh -c autoreconf -ivf
/bin/sh: autoreconf: not found

    at /github/workspace/node_modules/execa/index.js:231:11
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Promise.all (index 0)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/hexo-tag-aplayer/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/hexo-blog-encrypt/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gifsicle@4.0.1 postinstall: `node lib/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the gifsicle@4.0.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /github/home/.npm/_logs/2020-08-10T01_40_40_412Z-debug.log
```

这是 deploy.yml :

```yml
name: 自动部署 Hexo

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - name: 开始运行
        uses: actions/checkout@v1

      - name: 缓存
        uses: actions/cache@v1
        id: cache-dependencies
        with:
          path: node_modules
          key: ${{runner.OS}}-${{hashFiles('**/package-lock.json')}}

#      - name: 安装系统依赖
#        run: |
#          sudo apt-get install autoconf

      - name: 部署准备
        run: |
          git clone https://${{secrets.GH_TOKEN}}@github.com/RebornQ/rebornQ.github.io.git .deploy_git
          cp ./_config.yml ./_config_backup.yml
          sed -i 's/git@github.com:/https:\/\/${{secrets.GH_TOKEN}}@github.com\//g' ./_config.yml
      - name: 部署博客
        uses: yrpang/github-actions-hexo@master
        with:
          github_token: ${{secrets.GH_TOKEN}}
          username: ${{secrets.GIT_NAME}}
          email: ${{secrets.GIT_EMAIL}}
      - name: 清理
        run: |
          mv ./_config_backup.yml ./_config.yml
```

看起来是 dockerflie 的问题，查了一下资料，根据 [这个链接](https://stackoverflow.com/questions/60543573/dockerfile-error-command-failed-bin-sh-c-autoreconf-ivf-bin-sh-au) 里面说的，可能需要在 dockerfile 里加上这一句：
```dockerfile
RUN apk add --update autoreconf
```
